
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>PUS</title>
    <meta name="description" content="URL Shortener">
    <meta name="author" content="Phillip Partsch">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/skeleton.css">

    <link rel="icon" type="image/png" href="images/favicon.png">
</head>
<body>
<!-- Primary Page Layout
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
<div class="container">
    <div class="row">
        <div class="column" style="margin-top: 10%">
            <h1>PUS</h1>
            <h5><a>P</a>HP <a>U</a>RL <a>S</a>hortener</h5>
            <br><br>
            <a href="<?= htmlspecialchars($url); ?>"><?= htmlspecialchars($url); ?></a>
        </div>
    </div>
</div>
</body>
</html>
